### ISSUE TITLE
[ENHANCEMENT] Debug implementation is missing for Response

### ISSUE THREAD

**Issue by GopherJ** [elastic/elasticsearch-rs#113]
**Describe the bug**

**To Reproduce**
1. 
2. 
3. 

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10 Pro]
 - rustc version [e.g. `rustc --version`]

**Additional context**

**Comment by GopherJ** [comment]
It makes hard to debug

**Comment by russcam** [comment]
@GopherJ please can you take the time to fill the issue details in properly, thanks.

I don't think this should be labelled as a bug; it would be a useful enhancement to implement. What would you expect to see in a `Debug` implementation?
