### ISSUE TITLE
[ENHANCEMENT] strong typed Response.

### ISSUE THREAD

**Issue by GopherJ** [elastic/elasticsearch-rs#140]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when there  elasticsearch-rs is not strongly typed, I cannot deserialize my response to some kind of type.

elastic-rs has elastic-types if I rememembered correctly, cannot we port them here? Not strongly typed makes elasticsearch-rs not too many advantages over reqwest. It becomes only a wrapper of reqwest.....

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by GopherJ** [comment]
https://docs.rs/elastic_types/0.21.0-pre.4/elastic_types/

**Comment by GopherJ** [comment]
https://github.com/elastic-rs/elastic/blob/312eeb22b6ad60072a80680fbec27f466cdcb9b3/src/elastic/src/client/responses/search.rs#L78-L91 

is more urgent I think, can we have it in elastic-rs?

**Comment by GopherJ** [comment]
A thing like https://docs.rs/elasticsearch/7.9.0-alpha.1/elasticsearch/http/response/struct.Response.html isn't really useful

**Comment by GopherJ** [comment]
@russcam Any idea on this?

**Comment by russcam** [comment]
@GopherJ there is already an issue open to discuss request and response types: #75. Please have a read of the other issue and discuss there. Thanks!.

**Comment by GopherJ** [comment]
@russcam Hi, I think query builder & strongly typed response are two different things, can this be re-opened?
