### ISSUE TITLE
[BUG] IndicesPutTemplate has an unnecessary bound B

### ISSUE THREAD

**Issue by GopherJ** [elastic/elasticsearch-rs#153]
**Describe the bug**

https://docs.rs/elasticsearch/7.9.0-alpha.1/src/elasticsearch/generated/namespace_clients/indices.rs.html#6203-6205 has a bound B but it's not necessary and redundant to T in https://docs.rs/elasticsearch/7.9.0-alpha.1/src/elasticsearch/generated/namespace_clients/indices.rs.html#6230

**To Reproduce**
1. 
2. 
3. 

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10 Pro]
 - rustc version [e.g. `rustc --version`]

**Additional context**

**Comment by GopherJ** [comment]
I believe that we will only need one of them

**Comment by russcam** [comment]
Hi @GopherJ, 

`T` and `B` serve different purposes; `T` is a type that implements `Serialize`, whilst `B` is a type that implements `Body`.

`client.indices().put_template()` returns a new instance of `IndicesPutTemplate<'a, 'b, ()>` where `B` is `()`. Then when `body()` is later called, it returns a new instance of `IndicesPutTemplate` where `B` is `JsonBody<T>`. 

If the `body` call were constrained to `B`, then a user would need to wrap any type that implements `Serialize` in `JsonBody` e.g. `JsonBody(json!({ }))`, which feels more cumbersome to use that simply passing the type. Accepting `B` would however have the benefit of accepting other `Body` implementations like `String`, `&[u8]`, etc.

In the future, `T` may end up being a specific type for `IndicesPutTemplate` (#75), though it's not definite how this will be implemented; your thoughts are welcome on #75.

My inclination is to leave this as is for now.

**Comment by russcam** [comment]
Closing this as I think I have explained how `T` and `B` are used in the current implementation
