### ISSUE TITLE
[BUG] 8.0.0-alpha.1 does not exist in crates.io registry

### ISSUE THREAD

**Issue by kherro** [elastic/elasticsearch-rs#157]
**Describe the bug**
I have `elasticsearch = "8.0.0-alpha.1"` in my `Cargo.toml` file, as described [in the `Installing` section of the README](https://github.com/elastic/elasticsearch-rs#installing). After running `cargo build`, I get the following error:

```
    Updating crates.io index
error: no matching package named `elasticsearch` found
location searched: registry `https://github.com/rust-lang/crates.io-index`
required by package `chatops v0.1.0 (/Users/kherro/Workspace/chatops)`
```

**To Reproduce**
1. Add `elasticsearch = "8.0.0-alpha.1"` in the `[dependencies]` section of your `Cargo.toml` file.
2. Run `cargo build`

**Expected behavior**
I expect `cargo build` to successfully compile a local package and all of its dependencies.

**Screenshots**
![Screen Shot 2021-01-12 at 7 33 50 AM](https://user-images.githubusercontent.com/10460086/104320893-85be1d00-54a8-11eb-8bf4-ddd825ac5839.png)

![Screen Shot 2021-01-12 at 7 34 50 AM](https://user-images.githubusercontent.com/10460086/104321000-a9816300-54a8-11eb-8940-928f750a0c2a.png)

**Environment (please complete the following information):**
 - OS: macOS Big Sur version 11.0.1
 - rustc version [e.g. `rustc --version`]: rustc 1.49.0 (e1884a8e3 2020-12-29)

**Additional context**
I can successfully `cargo build` after replacing `elasticsearch = "8.0.0-alpha.1"` with `elasticsearch = "7.10.0-alpha.1"`, as found on [crates.io](https://crates.io/crates/elasticsearch).

**Comment by russcam** [comment]
Hey @kherro, thanks for raising 👍 

The README.md on the master branch is tracking Elasticsearch master branch, which has commits in for the next major version, 8.0. Versions of the client are released from [7.x](https://github.com/elastic/elasticsearch-rs/tree/7.x) and minor branches such as [7.10](https://github.com/elastic/elasticsearch-rs/tree/7.10) (which are cut from 7.x when 7.10.0 is released, for example), where the versions in the respective READMEs reflect the state of the branches.

An unfortunate side effect of this flow is that the README.md seen when landing on the repository will be the master branch, which may relate to a version not yet released. But, this flow keeps the version in all files in a branch in sync, which makes it a little less cognitively burdensome than needing to ensure the README on the master branch is updated each time a new version is released. 

[docs.rs](https://docs.rs/elasticsearch) and [crates.io](https://crates.io/crates/elasticsearch) will always contain the correct released versions, which are shown in the badges at the top of the README.

Hope this explains the setup.
