### ISSUE TITLE
[ENHANCEMENT] Add support for raw/bytes response

### ISSUE THREAD

**Issue by dodomorandi** [elastic/elasticsearch-rs#160]
**Is your feature request related to a problem? Please describe.**
ElasticSearch supports `cbor` format, and it would be useful it given the smaller overhead over json and that in Rust the decoder is available and also a serde Serializer/Deserializer. However, in order to receive and decode `cbor` data, it is necessary to get the raw data from [Response](https://docs.rs/elasticsearch/7.10.1-alpha.1/elasticsearch/http/response/struct.Response.html).

**Describe the solution you'd like**
Add the following to `Response`:
```rust
pub async fn bytes(self) -> Result<Bytes, ClientError>
{
    let bytes = self.0.bytes().await?;
    Ok(bytes)
}
```
Where `Bytes` is from the `bytes` crate as returned from `reqwest`.

**Comment by russcam** [comment]
I think this would be a useful addition to the client. Would you be interested in opening a PR for it, @dodomorandi?

**Comment by laurocaetano** [comment]
@dodomorandi please let me know if you are interested in opening the PR, and in case you are not, I could submit [my patch](https://github.com/elastic/elasticsearch-rs/compare/master...laurocaetano:lc-expose-bytes-to-response) instead.

**Comment by dodomorandi** [comment]
I will be glad to help if I can. However, in this case I think that the work already done by @laurocaetano is more complete than my _simple_ proposal.
I suggest @laurocaetano to open a PR with his patch, in case the introduced change are contested I can open a PR with only the `bytes` method :relaxed:
