### ISSUE TITLE
[ENHANCEMENT] Access to exact costs for the current month 

### ISSUE THREAD

**Issue by tatianafinamor** [elastic/elasticsearch-rs#178]
**Is your feature request related to a problem? Please describe.**
The customer would like to have access to the exact amount of charges accrued on the account during the billing cycle. 

**Describe the solution you'd like**
If we could give the customers access to billing alerts/ budgeting or cost explored.

**Describe alternatives you've considered**
They currently have access to the Usage page which shows the estimated usage.

**Comment by swallez** [comment]
@tatianafinamor I think you opened an issue in the wrong repository. This is the Elasticsearch Rust client library, and has nothing to do with billing 😉
