### ISSUE TITLE
[BUG] When accessing response via json, null value thwarts deserialization

### ISSUE THREAD

**Issue by PeterGrace** [elastic/elasticsearch-rs#183]
**Describe the bug**
A call to `response.json().await` fails with error: `error decoding response body: invalid type: null, expected any valid TOML value at line 1 column 161`.  Upon further inspection, the null value is the response for `max_score`, I assume because I'm not actually executing a search that returns values, just an aggregation of data from the search.

data returned in the query (gathered by using response.text().await instead):
```
{"took":410,"timed_out":false,"_shards":{"total":450,"successful":450,"skipped":435,"failed":0},"hits":{"total":{"value":10000,"relation":"gte"},"max_score":null,"hits":[]},"aggregations":{"ingestLag":{"buckets":[{"key":60.0,"doc_count":530540} <snip>
```

**To Reproduce**
```
    let mut response = client.search(SearchParts::Index(&["fastly-logs*"]))
        .body(json!({
  "query": {
    "bool": {
      "filter": [
        {
          "range": {
            "ingest_time": {
              "gte": "now-10m",
              "lte": "now",
              "format": "epoch_millis"
            }
          }
        },
        {
          "query_string": {
            "analyze_wildcard": true,
            "query": "*"
          }
        }
      ]
    }
  },
  "size": 0,
  "aggs": {
    "ingestLag": {
      "histogram": {
        "field": "elk_ingest_lag",
        "interval": 30
      }
    }
  }
  }))
        .send()
        .await?;

    response = response.error_for_status_code()?;

    //let response_body = response.text().await.unwrap();
    //info!("{}", response_body);

       let response_body = match response.json::<Value>().await {
         Ok(s) => s,
         Err(e) => bail!("CANT DECODE: {}",e)
       };
```
**Expected behavior**
The `response.json().await` call would produce a Value object containing the results of the query.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.10
 - rustc version: 1.54.0

**Comment by russcam** [comment]
Thanks for opening @PeterGrace.

I've created a test for this in https://github.com/elastic/elasticsearch-rs/tree/bug/183, which passes OK. Based on the error message

> error decoding response body: invalid type: null, expected any valid TOML value at line 1 column 161

Is it possible that the`Value` type in the response is a [`toml::value::Value`](https://docs.rs/toml/0.4.10/toml/value/enum.Value.html) and not a [`serde_json::value::Value`](https://docs.serde.rs/serde_json/value/enum.Value.html)?

**Comment by PeterGrace** [comment]
> Is it possible that the`Value` type in the response is a [`toml::value::Value`](https://docs.rs/toml/0.4.10/toml/value/enum.Value.html) and not a [`serde_json::value::Value`](https://docs.serde.rs/serde_json/value/enum.Value.html)?

Well that's embarrassing!  I must have hit the wrong option when I was importing in CLion and accidentally imported the toml Value instead.  I was wondering why TOML would even be involved.  Sorry for the noise, I'll close this one out.
