### ISSUE TITLE
[BUG] BulkCreateOperation requires `_id` field, although it is optional

### ISSUE THREAD

**Issue by mfelsche** [elastic/elasticsearch-rs#190]
**Describe the bug**
Both the [`BulkOperation::create`](https://github.com/elastic/elasticsearch-rs/blob/master/elasticsearch/src/root/bulk.rs#L165) as well as [`BulkCreateOperation::new`](https://github.com/elastic/elasticsearch-rs/blob/master/elasticsearch/src/root/bulk.rs#L220) require an `_id` argument, although this is optional according to the docs in https://www.elastic.co/guide/en/elasticsearch/reference/7.14/docs-bulk.html#bulk-api-request-body

**Expected behavior**

Provide a way to create a `BulkCreateOperation` without the `_id`, e.g. make the argument an `Option<S>`.

**Environment (please complete the following information):**
 - OS: OSX
 - rustc version 1.56.1

**Comment by russcam** [comment]
Hi @mfelsche, this is the same issue as #174; I'm going to close to consolidate on that issue.

**Comment by mfelsche** [comment]
Thank you! I honestly didn't find #174 when i filed this one, my bad.
