### ISSUE TITLE
[BUG] Make tokio optional or provide a trait for implementing AsyncRuntimes

### ISSUE THREAD

**Issue by vertexclique** [elastic/elasticsearch-rs#199]
**Describe the bug**

**To Reproduce**
1. 
2. 
3. 

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10 Pro]
 - rustc version [e.g. `rustc --version`]

**Additional context**

**Comment by swallez** [comment]
This library depends on `reqwest`, which is based on `hyper`, which depends on `tokio`. So the async runtime has to be tokio.

Feel free to reopen this issue if you can provide more concrete explanations on how using a different runtime could be achieved.
