### ISSUE TITLE
[BUG] New version?

### ISSUE THREAD

**Issue by Dig-Doug** [elastic/elasticsearch-rs#234]
Elastic search is now on version 8.14.2. The rust crate has not been updated in over a year and is on `elasticsearch = "8.5.0-alpha.1"`

Should there be a new version?

**Comment by swallez** [comment]
A new version has been released for version 8.15.0 of Elasticsearch.

https://github.com/elastic/elasticsearch-rs/releases/tag/v8.15.0-alpha.1
