### ISSUE TITLE
[DOCS] Api key format doesn't match current UI

### ISSUE THREAD

**Issue by Dig-Doug** [elastic/elasticsearch-rs#235]
The ApiKey credential currently asks for a key id and an api key. However, in the elasticsearch cloud UI, API keys don't provide these components separately. Instead, they provide `base64(keyid + ":" + key)` as one string. Since you also give API keys a name, my initial thought was to provide the api key name as the id and then the base64 key as the value.

Either the rust client should be updated to take this format or the docs should be updated to make it clear how to get these values.

**Comment by swallez** [comment]
In PR #238 we added a new `EncodedApi` credential that takes a single string so that both representations of API keys can be used.
