### ISSUE TITLE
objekt renamed to dyn-clone

### ISSUE THREAD

**Issue by mwilliammyers** [elastic/elasticsearch-rs#39]
I might be missing something but `objekt` does [not](https://crates.io/search?q=objekt) seem to be on crates.io?

**Comment by mwilliammyers** [comment]
No idea how this happened but I was 100% sure it was not showing up via search. A space must have snuck in during copy/paste...

**Comment by mwilliammyers** [comment]
Ok. I’m not crazy. It looks like it was renamed  to [dyn-clone](https://crates.io/crates/dyn-clone) so search wasn’t working unless you directly use the query param in the URL.

**Comment by russcam** [comment]
Thanks for opening @mwilliammyers, looks like there's a PR open for it already 👍
