### ISSUE TITLE
[REFACTOR] Rename status_code to status?

### ISSUE THREAD

**Issue by mwilliammyers** [elastic/elasticsearch-rs#47]
Should we rename `status_code` everywhere to `status` to match `reqwest`?

**Comment by russcam** [comment]
Thanks for opening the conversation, @mwilliammyers. 

I intentionally named it `status_code` to differentiate it from any notion of a status that can be returned from Elasticsearch. For example, many responses return the status code in a `status` field on the response; I understand that a response body needs to be read to get to this, but I wanted to avoid any confusion between a status related to Elasticsearch, and a status related to the HTTP library. What do you think?

**Comment by mwilliammyers** [comment]
Ahhh makes sense. I agree 100% then.

**Comment by russcam** [comment]
Cool cool. I'll close this issue 👍
