### ISSUE TITLE
[BUG] There is no obvious way to support a reverse proxy

### ISSUE THREAD

**Issue by BearOve** [elastic/elasticsearch-rs#48]
**Describe the bug**
When running towards elasticsearch behind a reverse proxy where the url is something like `http://10.1.2.3/es/` I haven't found a way to use it. The reason for this appears to be the way `Url::join` works. When given a path that starts with `/` it removes everything after the domain and adds it to the root.

**To Reproduce**

```rust
    // The logging from reqwuest shows how the url is not as expected
    let client = Elasticsearch::new(Transport::single_node("http://10.1.2.3/es/")?);
    let search = client.search(SearchParts::Index(&["my-index"]));
    let res = search.send().await?;
    // [2020-01-14T10:25:31Z DEBUG reqwest::async_impl::response] Response: '200 OK' for https://10.1.2.3/my-index/_search

    // Digging further shows the issue is likely in how Url::join works
    let url = url::Url::parse("http://10.1.2.3/hello/").unwrap();
    assert_eq!(url.join("world").unwrap().as_str(), "http://10.1.2.3/hello/world");
    assert_eq!(url.join("/world").unwrap().as_str(), "http://10.1.2.3/world");

    // Note: The trailing backslash is important or it will be consithered a file name
    let url = url::Url::parse("http://10.1.2.3/hello/again").unwrap();
    assert_eq!(url.join("world").unwrap().as_str(), "http://10.1.2.3/hello/world");
    assert_eq!(url.join("/world").unwrap().as_str(), "http://10.1.2.3/world");
```

**Expected behavior**
The url used should be `https://10.1.2.3/es/my-index/_search`

**Environment (please complete the following information):**
 - OS: Probably doesn't matter. Tested on Windows and Linux
 - rustc version: rustc 1.42.0-nightly (859764425 2020-01-07)

**Comment by BearOve** [comment]
A work-around that works for my particular use-case right now is to add `es/` as a prefix to the index. I doubt this will cut it when I extend my usage though.

**Comment by russcam** [comment]
I've opened #50 to address
