### ISSUE TITLE
[DISCUSS] Currently requires nightly release of rustc due to external_doc

### ISSUE THREAD

**Issue by lucca-fraser** [elastic/elasticsearch-rs#87]
This crate appears to require the nightly release of rustc, solely due to its use of the external_doc feature. It would be convenient if the crate were buildable with the stable release. Is there any way to avoid the use of this feature for the time being?

**Comment by mwilliammyers** [comment]
Valid question :)

The plan is to move off of nightly, but in addition to that usage, there are at least a few (indirect) dependencies that rely on nightly, see [this comment](https://github.com/elastic/elasticsearch-rs/issues/59#issuecomment-588092730).

**Comment by russcam** [comment]
I've opened https://github.com/elastic/elasticsearch-rs/pull/89 to address. With a `build.rs` script to detect rustc version and some `cfg_attr`, elasticsearch can work with rust stable whilst still also allowing README to be tested with `external_doc` feature with

```rust
cargo +nightly test -p elasticsearch --doc
```

api_generator still needs rust nightly, but this isn't an impediment as it's not a published package.
