### ISSUE TITLE
[BUG] Failure in certificate validation

### ISSUE THREAD

**Issue by srikwit** [elastic/elasticsearch-rs#90]
**Describe the bug**
Four tests related to certificate validation fail.

**To Reproduce**
1. `cargo test`

**Expected behavior**
test result ok. 7 passed.

**Environment (please complete the following information):**
 - Debian GNU/Linux 10 (buster)
 - rustc 1.42.0 (b8cedc004 2020-03-09)

**Additional context**
```
running 7 tests
test full_certificate_ca_validation ... ok
test fail_certificate_certificate_validation ... FAILED
test certificate_certificate_ca_validation ... ok
test default_certificate_validation ... FAILED
test certificate_certificate_validation ... FAILED
test none_certificate_validation ... ok
test full_certificate_validation ... FAILED

failures:

---- fail_certificate_certificate_validation stdout ----
Error: ErrorMessage { msg: "Expected error but response was 200 OK" }
thread 'fail_certificate_certificate_validation' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', <::std::macros::panic macros>:5:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- default_certificate_validation stdout ----
Error: ErrorMessage { msg: "Expected error but response was 200 OK" }
thread 'default_certificate_validation' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', <::std::macros::panic macros>:5:6

---- certificate_certificate_validation stdout ----
Error: ErrorMessage { msg: "Expected error but response was 200 OK" }
thread 'certificate_certificate_validation' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', <::std::macros::panic macros>:5:6

---- full_certificate_validation stdout ----
Error: ErrorMessage { msg: "Expected error but response was 200 OK" }
thread 'full_certificate_validation' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', <::std::macros::panic macros>:5:6


failures:
    certificate_certificate_validation
    default_certificate_validation
    fail_certificate_certificate_validation
    full_certificate_validation

test result: FAILED. 3 passed; 4 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by russcam** [comment]
Thanks for opening @srikwit. Are you running the tests against an instance of Elasticsearch that is configured to use the `testnode_san.crt` and `testnode_san.key` in `.ci/certs` ?

**Comment by srikwit** [comment]
No, I was running it against my own instance which might not be configured with these certs. Kindly allow me to reconfigure my environment before re-testing the test cases.

**Comment by russcam** [comment]
No problem, please do. 

Need to write some notes in `contributing.md` about the tests 😃

**Comment by srikwit** [comment]
Hi @russcam , I ran the tests using `./.ci/run-tests` and it resulted in the following error message:
```
....
Successfully built b7d7bb1bcd91
Successfully tagged elastic/elasticsearch-rs:latest
+ echo -e '\033[1m>>>>> Run [elastic/elasticsearch-rs container] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>\033[0m'
>>>>> Run [elastic/elasticsearch-rs container] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>
./.ci/run-tests: line 55: RUST_BACKTRACE: unbound variable
++ cleanup
....
SUCCESS: Cleaned up and exiting

FAILURE during run-tests
```
Kindly let me know what debugging information you would need.

**Comment by russcam** [comment]
My apologies @srikwit - I made changes to the PowerShell ci scripts and Dockerfile, but did not reflect those changes in the shell scripts. I've now updated them.

If you want to test from local and spin up an Elasticsearch instance with the shell script, you can do

```sh
# specify Elasticsearch version to use, for example, use
# default 7.6.2 distribution
export ELASTICSEARCH_VERSION="elasticsearch:7.6.2"

# allow instance to stay up after script finishes
export DETACH=true

# spin up Elasticsearch docker instance
.ci/run-elasticsearch.sh

# make the instance available to tests
export ES_TEST_SERVER="https://localhost:9200"

# run tests
cargo +nightly test --all-features
```

You can also use the run-tests script too (_need to ensure elasticsearch docker instance isn't already running_)

```sh
export ELASTICSEARCH_VERSION="7.6.2"

.ci/run-tests
```

run-tests with the certificate tests seems to be a little flaky though, with tests sometimes failing due to DNS errors with docker network. [Might need to detect and specify `--dns` in the scripts](https://development.robinwinslow.uk/2016/06/23/fix-docker-networking-dns/)

**Comment by srikwit** [comment]
No problem @russcam. I will retest it and let you know the difference by today evening.

**Comment by srikwit** [comment]
Hi @russcam,
I am still getting errors in the certificate tests as follows:

------------------------------------------------------
running 7 tests
test certificate_certificate_ca_validation ... FAILED
test full_certificate_ca_validation ... FAILED
test none_certificate_validation ... FAILED
test fail_certificate_certificate_validation ... FAILED
test default_certificate_validation ... FAILED
test full_certificate_validation ... FAILED
test certificate_certificate_validation ... FAILED

failures:

---- certificate_certificate_ca_validation stdout ----
Error: Error { kind: Http(reqwest::Error { kind: Request, url: "http://localhost:9200/", source: hyper::Error(IncompleteMessage) }) }
thread 'certificate_certificate_ca_validation' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/macros.rs:16:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- full_certificate_ca_validation stdout ----
Error: Error { kind: Http(reqwest::Error { kind: Request, url: "http://localhost:9200/", source: hyper::Error(IncompleteMessage) }) }
thread 'full_certificate_ca_validation' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/macros.rs:16:9

---- none_certificate_validation stdout ----
Error: Error { kind: Http(reqwest::Error { kind: Request, url: "http://localhost:9200/", source: hyper::Error(IncompleteMessage) }) }
thread 'none_certificate_validation' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/macros.rs:16:9

---- fail_certificate_certificate_validation stdout ----
thread 'fail_certificate_certificate_validation' panicked at 'Expected error message to contain 'unable to get local issuer certificate' but was 'error sending request for url (http://localhost:9200/): connection closed before message completed'', elasticsearch/tests/cert.rs:211:13

---- default_certificate_validation stdout ----
thread 'default_certificate_validation' panicked at 'Expected error message to contain 'unable to get local issuer certificate' but was 'error sending request for url (http://localhost:9200/): connection closed before message completed'', elasticsearch/tests/cert.rs:42:13

---- full_certificate_validation stdout ----
thread 'full_certificate_validation' panicked at 'Expected error message to contain 'unable to get local issuer certificate' but was 'error sending request for url (http://localhost:9200/): connection closed before message completed'', elasticsearch/tests/cert.rs:114:21

---- certificate_certificate_validation stdout ----
thread 'certificate_certificate_validation' panicked at 'Expected error message to contain 'unable to get local issuer certificate' but was 'error sending request for url (http://localhost:9200/): connection closed before message completed'', elasticsearch/tests/cert.rs:166:21


failures:
    certificate_certificate_ca_validation
    certificate_certificate_validation
    default_certificate_validation
    fail_certificate_certificate_validation
    full_certificate_ca_validation
    full_certificate_validation
    none_certificate_validation

test result: FAILED. 0 passed; 7 failed; 0 ignored; 0 measured; 0 filtered out

------------------------------------------------------

However, the `.ci/run-tests` have run without errors.

**Comment by russcam** [comment]
The issue is likely that `ES_TEST_SERVER` is set to `"http://localhost:9200/"` **but it should be set to `"https://localhost:9200"`** since the script configures TLS when using the default distribution, and tests need to run against a HTTPS endpoint in order to test certificate validation

**Comment by srikwit** [comment]
@russcam it works now. Thanks for fixing the issue.
